### PR TITLE
Ensure build includes armv7s slices

### PR DESCRIPTION
**Pull request by jtreanor**
This is a fix for #40. Let me know what you think.

### CODE REVIEW

**Comment by neonichu** [comment]
We should add a spec for this, so that future Xcode updates don't hit by surprise. Presence of architectures can be checked with `lipo path/to/library -verify_arch armv7 arm64 armv7s`

**Comment by jtreanor** [comment]
:+1: I'll do that.

**Comment by jtreanor** [comment]
I have added a spec and changed my approach so that it doesn't break mac packages.

**Comment by neonichu** [comment]
Awesome! :+1:

**Comment by jtreanor** [comment]
Just realised I forgot to check for `armv7s` here: https://github.com/CocoaPods/cocoapods-packager/blob/master/spec/command/package_spec.rb#L75

It's a tiny change, will I add a new PR for it?

**Comment by neonichu** [comment]
I'll do it directly on master #yolo

**Comment by jtreanor** [comment]
:smile: :+1:

**Comment by neonichu** [comment]
Done in c3f3721b2e45eb79fd2ecaa1be57a09049d3c416

**Pull request merged**
