### PR TITLE
Abort on xcodebuild error

### LINKED ISSUE #47: Pod package does not fail when xcodebuild fails
I ran into an into issue where symbols were missing from my packaged pod.

I tracked it down to ```xcodebuild``` failing (https://github.com/CocoaPods/cocoapods-packager/blob/master/lib/cocoapods-packager/builder.rb#L149). However, the ```pod package``` command appeared as though it ran successfully. It would be great if the return code of xcodebuild is checked for success, and a way to see the xcodebuild output when a failure occurs.

### PR DESCRIPTION
**Pull request by jtreanor**
This fixes #47 in quite a simplistic way. Let me know what you think.

### CODE REVIEW

**Comment by neonichu** [comment]
I don't think using `abort()` is very nice, because all the cleanup won't be executed in that case (see <https://github.com/CocoaPods/cocoapods-packager/blob/master/lib/pod/command/package.rb#L72-L73>). Maybe we can move it to an exit handler, though.

Also we should have a spec for that case.

**Comment by kylef** [comment]
Yes, probably better to raise an Informative exception, which would be catched, cleaned up and then re-raised in https://github.com/CocoaPods/cocoapods-packager/blob/master/lib/pod/command/package.rb#L70.

**Comment by jtreanor** [comment]
Yeah, I wasn't sure about that. I'll try something a bit gentler with a spec.

**Comment by jtreanor** [comment]
Closing this as I haven't got around to a better fix yet.

**Pull request closed without merging**
