### PR TITLE
Add option to exclude symbols in dependencies from static libraries/frameworks

### PR DESCRIPTION
**Pull request by mayurp**
Added --exclude-deps option which excludes symbols from pod dependencies in the packaged static library or framework

This is an alternative to using symbol mangling which can lead to issues with code that relies on reflection, and also has the downside of bloating the app binary

Also fixed issue where the  "podspec has binary-only depedencies, mangling not possible" error is raised even when --no-mangle is specified.

### CODE REVIEW

**Comment by neonichu** [comment]
Thanks! Please also update the tests and/or provide a default value for the new parameter.

**Comment by tagyro** [comment]
bump

**Comment by mayurp** [comment]
Hi, the new parameter is false by default package.rb
@@ -27,6 +28,7 @@ module Pod
         @library = argv.flag?('library')
         @dynamic = argv.flag?('dynamic')
         @mangle = argv.flag?('mangle', true)
+        @exclude_deps = argv.flag?('exclude-deps', false)

**Comment by mayurp** [comment]
Hi, sorry for the delay in replying. The new parameter is set to false by default in package.rb:
Is this ok?

@@ -27,6 +28,7 @@ module Pod
         @library = argv.flag?('library')
         @dynamic = argv.flag?('dynamic')
         @mangle = argv.flag?('mangle', true)
+        @exclude_deps = argv.flag?('exclude-deps', false)

**Comment by jmjones5** [comment]
bump

**Comment by rsandhu-va** [comment]
Any update here? 

Still running into the issue where --no-mangle has no effect.

**Comment by neonichu** [comment]
Would love to merge this PR, but it is actually breaking some of the functionality — see <https://travis-ci.org/CocoaPods/cocoapods-packager/builds/88038160#L323>

**Comment by rsandhu-va** [comment]
Apart from the PR, can we enable the functionality of 'no-mangle' option?

**Comment by gigi-mohemian** [comment]
Any progress on this? Could I help to fix this PR in any way?

**Comment by neonichu** [comment]
@gigi-mohemian sure, thanks for offering to help! The tests are failing because some parts of the code haven't been updated for the new parameter introduced by this PR — if you have time to fix this and submit a new PR that would be 👌

**Comment by mayurp** [comment]
Apologies, I've finally had a chance to get back to this. fixed the build errors and added tests. Please let

**Comment by neonichu** [comment]
@mayurp awesome, thanks a lot for the contribution 🎉

**Pull request merged**
